question_data = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "Han Solo's co-pilot and best friend, 'Chewbacca', is an Ewok.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "The film '2001: A Space Odyssey' was released on December 31st, 2000.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "The 2010 film 'The Social Network' is a biographical drama film about MySpace founder Tom Anderson.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "Samuel L. Jackson had the words, 'Bad Motherf*cker' in-scripted on his lightsaber during the filming of Star Wars.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
              "question": "'Cube', 'Cube 2: Hypercube' and 'Cube Zero' were directed by the same person.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
              "question": "Actor Tommy Chong served prison time.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
              "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
              "correct_answer": "True", "incorrect_answers": ["False"]}]



